version: "3.8"

services:
    app:
        build: .
        ports:
            - "9850:3000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: sh -c "npm i && npm run build && npm run start"
