version: "3.8"

services:
  app:
    build: .
    ports:
      - "9850:3000"
    volumes:
      - /volume1/TV/网课:/usr/src/app/public/videos
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
